---
- name: Run Prewig Validator
  hosts: all
  gather_facts: no


  roles: 
    - {role: 'winstepone', tags: 'winstepone'}
    - {role: 'windisableadmin', tags: 'windisableadmin'}
    - {role: 'winremoveawscred', tags: 'winremoveawscred'}
    - {role: 'winssmagent', tags: 'winssmagent'}
    - {role: 'winec2config', tags: 'winec2config'}
    - {role: 'wininstallpackages', tags: 'wininstallpackages'}
    - {role: 'winfixpathvariable', tags: 'winfixpathvariable'}
    - {role: 'winrunvalidator', tags: 'winrunvalidator'}
   
