---
# tasks file for runvalidator
  - name: Run the validator
    shell: |
      python3 /home/svc_awsmigfactory/Linux_PreWig_Validator/control_script.py --verbose
    register: ps
  - name: Print the result
    debug: var=ps.stdout_lines
